//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Data.DataAccess
{
    using App.Entities.Base;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CnxBDEmpresaEntities : DbContext
    {
        public CnxBDEmpresaEntities()
            : base("name=CnxBDEmpresaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cliente> Clientes { get; set; }
        public virtual DbSet<Detalle_Orden> Detalle_Orden { get; set; }
        public virtual DbSet<Estatu> Estatus { get; set; }
        public virtual DbSet<Moneda> Monedas { get; set; }
        public virtual DbSet<Orden> Ordens { get; set; }
        public virtual DbSet<Producto> Productoes { get; set; }
        public virtual DbSet<Producto_Tipo> Producto_Tipo { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Tipo_Comprobante> Tipo_Comprobante { get; set; }
        public virtual DbSet<Tipo_Documento> Tipo_Documento { get; set; }
    }
}
