//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Entities.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cliente()
        {
            this.Ordens = new HashSet<Orden>();
        }
    
        public int ID_Cliente { get; set; }
        public string Nombre_Completo { get; set; }
        public string NroDocumento { get; set; }
        public string Direccion { get; set; }
        public int Id_TipoDocumento { get; set; }
        public int Id_Estatus { get; set; }
    
        public virtual Estatu Estatu { get; set; }
        public virtual Tipo_Documento Tipo_Documento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orden> Ordens { get; set; }
    }
}
