//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Entities.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orden
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orden()
        {
            this.Detalle_Orden = new HashSet<Detalle_Orden>();
        }
    
        public int Id_Orden { get; set; }
        public Nullable<int> Id_TipoComprobante { get; set; }
        public Nullable<int> Id_Cliente { get; set; }
        public string Serie { get; set; }
        public string Numero { get; set; }
        public Nullable<System.DateTime> Fecha_Emision { get; set; }
        public Nullable<int> Id_Moneda { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public Nullable<decimal> IGV { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string Observacion { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_Orden> Detalle_Orden { get; set; }
        public virtual Moneda Moneda { get; set; }
        public virtual Tipo_Comprobante Tipo_Comprobante { get; set; }
    }
}
